
import React, { useState, useRef, useEffect } from 'react';
import { Message } from '../types';
import { getGeminiResponse } from '../services/gemini';

export const AIChat: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([
    { role: 'assistant', content: 'Willkommen! I am the Digital Twin of Hans-Peter Martini. How can I help you today regarding Martini Labs or our software solutions?' }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSend = async () => {
    if (!input.trim() || isLoading) return;

    const userMsg: Message = { role: 'user', content: input };
    setMessages(prev => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    const response = await getGeminiResponse([...messages, userMsg]);
    setMessages(prev => [...prev, { role: 'assistant', content: response }]);
    setIsLoading(false);
  };

  return (
    <div className="w-full mt-4 animate-slide-up">
      <div className="glass rounded-2xl overflow-hidden neon-border-cyan border-opacity-30">
        <div className="p-3 bg-cyan-900/20 border-b border-cyan-500/20 flex items-center justify-between">
          <span className="font-orbitron text-xs tracking-widest text-cyan-400 uppercase">Neural Interface Active</span>
          <div className="flex gap-1">
            <div className="w-2 h-2 rounded-full bg-red-500 shadow-[0_0_5px_red]"></div>
            <div className="w-2 h-2 rounded-full bg-yellow-500"></div>
            <div className="w-2 h-2 rounded-full bg-green-500"></div>
          </div>
        </div>
        
        <div 
          ref={scrollRef}
          className="h-64 overflow-y-auto p-4 space-y-4 scrollbar-thin scrollbar-thumb-cyan-900 scrollbar-track-transparent"
        >
          {messages.map((msg, i) => (
            <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
              <div className={`max-w-[85%] p-3 rounded-xl text-sm ${
                msg.role === 'user' 
                  ? 'bg-cyan-600/20 text-cyan-50 border border-cyan-500/30' 
                  : 'bg-zinc-800/50 text-zinc-300 border border-zinc-700'
              }`}>
                {msg.content}
              </div>
            </div>
          ))}
          {isLoading && (
            <div className="flex justify-start">
              <div className="bg-zinc-800/50 p-3 rounded-xl flex gap-1 items-center border border-zinc-700">
                <div className="w-1 h-1 bg-cyan-400 rounded-full animate-bounce"></div>
                <div className="w-1 h-1 bg-cyan-400 rounded-full animate-bounce [animation-delay:-.3s]"></div>
                <div className="w-1 h-1 bg-cyan-400 rounded-full animate-bounce [animation-delay:-.5s]"></div>
              </div>
            </div>
          )}
        </div>

        <div className="p-4 bg-black/40 border-t border-zinc-800 flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && handleSend()}
            placeholder="Type a message..."
            className="flex-1 bg-zinc-900 border border-zinc-700 rounded-lg px-4 py-2 text-sm focus:outline-none focus:border-cyan-500 text-white placeholder-zinc-600"
          />
          <button
            onClick={handleSend}
            disabled={isLoading}
            className="p-2 bg-cyan-600 hover:bg-cyan-500 disabled:opacity-50 rounded-lg transition-colors shadow-lg shadow-cyan-900/20"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
              <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
            </svg>
          </button>
        </div>
      </div>
      <p className="mt-2 text-[10px] text-zinc-600 text-center italic">
        * Powered by Martini Labs AI (Gemini 3 Flash). Not all responses are generated by the physical Hans-Peter.
      </p>
    </div>
  );
};
